name: CI

on:
  push:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Build & Test
        run: |
          docker build -t malam_test .
          docker run -d -p 3000:3000 --name malam_run malam_test 
          sleep 10
          STATUS_CODE=$(curl --silent --output --write-out "${http_code} http://localhost:3000 
          if [ $STATUS_CODE -ne 200 ]
          then
            docker stop malam_run
            docker rm malam_run
            exit 1
          fi
          docker stop malam_run
          docker rm malam_run

      