name: CI

on:
  push:
    branches:
      - "master"

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Build & Test
        run: |
          docker build -t malam_test .
          docker run -d -p 3000:3000 --name malam_run malam_test 
          sleep 10
          STATUS_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" http://localhost:3000)
          if [ $STATUS_CODE -ne 200 ]
          then
            docker stop malam_run
            docker rm malam_run
            exit 1
          else
            echo "test successful"  
          fi
          docker stop malam_run
          docker rm malam_run

      - name: Tag image before Push
        run: |
          docker tag malam_test:latest malam_test: ${{github.sha }}
      
      - name: Push to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Push backend image
        if: success()
        run: |
          docker push malam_test:${{ github.sha }}

